spring:
  application:
    name: logistics-tracking-service

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: PostgresPool
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
