spring:
  application:
    name: logistics-tracking-service

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.logisticstrackingservice.kafka.event"
        spring.json.value.default.type: "com.example.logisticstrackingservice.kafka.event.ShipmentStatusChangedEvent"
        spring.json.use.type.headers: false

  datasource:
    url: jdbc:postgresql://localhost:5432/logistics_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: PostgresPool
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

